Grails 4 compatibility
gpc/taggable pull request #17
Opened 2022-01-27 15:29 UTC by jjelliott

This makes the plugin work with Grails 4 by replacing a removed GORM method with a newer equivalent. 

I can tweak the dependency versions to match a different release in the 4.x.x cycle if that's required. 

I also updated the tests to use the current versions of the testing frameworks, rather than the legacy grails-test-mixins.

2022-01-27 15:32 UTC, JasonTypesCodes requested changes

2022-01-27 15:34 UTC, jjelliott commented on build.gradle
> +		classpath "org.grails.plugins:hibernate5:7.0.5"
That version does not line up with the `gorm.version` variable, should I add another?

2022-01-27 15:42 UTC, JasonTypesCodes commented on build.gradle
> +		classpath "org.grails.plugins:hibernate5:7.0.5"
I think that is a good idea, yes

2022-01-27 15:49 UTC, jjelliott commented on build.gradle
> +		classpath "org.grails.plugins:hibernate5:7.0.5"
This has been addressed.

2022-01-27 16:32 UTC, JasonTypesCodes approved these changes
Nice work!

2022-01-28 07:46 UTC, sbglasius approved these changes
My only comment is, that you changed the TagsTaglibTest to a Spock speck, then why not the TaggableTests? 
No need to change it, just wondering 🙂

2022-01-28 15:25 UTC, jjelliott commented
@sbglasius I converted the unit tests because something was broken, but the integration tests worked without needing to convert them. I did that a while back so I can't remember _what_ exactly was wrong, but that's why.

2022-02-24 14:34 UTC, merged